const nodemailer = require("nodemailer");

async function sendEmail(jobs) {
  try {
    let transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 465,
      secure: true,
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const html = generateHTML(jobs);

    await transporter.sendMail({
      from: `"AI Job Agent" <${process.env.EMAIL_USER}>`,
      to: process.env.EMAIL_USER,
      subject: "🔥 Daily Top Internships (AI Curated)",
      html,
    });

    console.log("📩 Email sent successfully!");
  } catch (err) {
    console.log("Email error:", err.message);
  }
}

function generateHTML(jobs) {
  let html = `
  <div style="font-family:Arial;background:#f6f7fb;padding:20px;">
    <div style="max-width:700px;margin:auto;background:#fff;padding:20px;border-radius:10px;">
      
      <h1 style="text-align:center;color:#222;">
        🔥 AI Curated Internships
      </h1>
      <p style="text-align:center;color:#666;">
        Top opportunities picked for you today
      </p>
      <hr/>
  `;

  jobs.forEach((job, i) => {
    html += `
      <div style="border:1px solid #eee;padding:15px;margin-bottom:15px;border-radius:10px;">
        
        <div style="display:flex;justify-content:space-between;align-items:center;">
          <h2 style="margin:0;font-size:18px;color:#333;">
            ${i + 1}. ${job.title}
          </h2>

          <span style="
            background:#e8f0ff;
            color:#1a73e8;
            padding:5px 10px;
            border-radius:20px;
            font-size:12px;
            font-weight:bold;
          ">
            Score: ${job.score}
          </span>
        </div>

        <p style="margin:5px 0;"><b>🏢 Company:</b> ${job.company}</p>
        <p style="margin:5px 0;"><b>📍 Location:</b> ${job.location}</p>
        <p style="margin:5px 0;"><b>💰 Stipend:</b> ${job.stipend}</p>

        <p style="margin-top:10px;"><b>🧠 Skills Required:</b></p>

        <div style="margin-bottom:10px;">
          ${
            job.skills && job.skills.length
              ? job.skills
                  .map(
                    (skill) => `
                    <span style="
                      display:inline-block;
                      background:#f1f1f1;
                      color:#333;
                      padding:5px 10px;
                      margin:3px;
                      border-radius:15px;
                      font-size:12px;
                    ">
                      ${skill}
                    </span>
                  `
                  )
                  .join("")
              : `<span style="color:#999;">Not specified</span>`
          }
        </div>

        <a href="${job.applyLink}" target="_blank"
          style="
            display:inline-block;
            margin-top:10px;
            background:#1a73e8;
            color:#fff;
            padding:8px 15px;
            border-radius:6px;
            text-decoration:none;
            font-size:13px;
          ">
          🚀 Apply Now
        </a>

      </div>
    `;
  });

  html += `
      <p style="text-align:center;color:#888;font-size:12px;">
        Generated by AI Job Agent 🤖
      </p>
    </div>
  </div>
  `;

  return html;
}

module.exports = { sendEmail };
