name: Daily AI Job Agent

on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  run-job-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create folders
        run: mkdir -p data reports screenshots

      - name: Clean install
        run: |
          npm cache clean --force
          npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run job agent
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: node src/index.js